version: "3.7"

services:

  frontend:
    container_name: frontend_server
    network_mode: "host"
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./shared:/shared:rw
    environment:
      - GROUP=RAND_NUMBER_GROUP

  backend:
    network_mode: "host"
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - GROUP=RAND_NUMBER_GROUP

  buyer:
    container_name: buyer_client
    network_mode: "host"
    build:
      context: .
      dockerfile: ./buyer/Dockerfile
    volumes:
      - ./shared:/shared:rw

  seller:
    container_name: seller_client
    network_mode: "host"
    build:
      context: .
      dockerfile: ./seller/Dockerfile
    volumes:
      - ./shared:/shared:rw
